services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

volumes:
  mongo_data: